const data = [
    {
        img: '/public/image1.png',
        name: 'Увлажнитель воздуха STARWIND SHC1322, 3л, белый',
        price: '1650 ₽',
        click: false,
        quantity: 0,
        id: 'id1',
    },
    {
        img: '/public/image2.png',
        name: 'Триммер PHILIPS HC3521/15 серебристый/черный',
        price: '2290 ₽',
        click: false,
        quantity: 0,
        id: 'id2',
    },
    {
        img: '/public/image3.png',
        name: 'Фитнес-трекер HONOR Band 5 CRS-B19S, 0.95", розовый',
        price: '2390 ₽',
        click: false,
        quantity: 0,
        id: 'id3',
    },
    {
        img: '/public/image4.png',
        name: 'Мышь A4TECH Bloody V3, игровая, оптическая, проводная, USB, черный',
        price: '960 ₽',
        click: false,
        quantity: 0,
        id: 'id4',
    },
    {
        img: '/public/image5.png',
        name: 'Фитнес-трекер HONOR Band 5 CRS-B19S, 0.95", черный',
        price: '2390 ₽',
        click: false,
        quantity: 0,
        id: 'id5',
    },
    {
        img: '/public/image6.png',
        name: 'Пылесос SINBO SVC 3497, 2500Вт, синий/серый',
        price: '5670 ₽',
        click: false,
        quantity: 0,
        id: 'id6',
    },
    {
        img: '/public/image7.png',
        name: 'Планшет DIGMA Optima 7 Z800 Android 10.0 серебристый',
        price: '9490 ₽',
        click: false,
        quantity: 0,
        id: 'id7',
    },
    {
        img: '/public/image8.png',
        name: 'Монитор игровой ACER Nitro RG241YPbiipx 23.8" черный',
        price: '16 800 ₽',
        click: false,
        quantity: 0,
        id: 'id8',
    },
    {
        img: '/public/image9.png',
        name: 'Экшн-камера DIGMA DiCam 310 4K, WiFi, черный',
        price: '2290 ₽',
        click: false,
        quantity: 0,
        id: 'id9',
    },
    {
        img: '/public/image10.png',
        name: 'Умная колонка ЯНДЕКС c голосовым помощником Алисой, серебристый',
        price: '5670 ₽',
        click: false,
        quantity: 0,
        id: 'id10',
    },
    {
        img: '/public/image11.png',
        name: 'Квадрокоптер DJI Mini 2 MT2PD Fly More Combo с камерой, серый',
        price: '60 990 ₽',
        click: false,
        quantity: 0,
        id: 'id11',
    },
    {
        img: '/public/image12.png',
        name: 'Шлем виртуальной реальности HTC Vive PRO Eye EEA, черный/синий',
        price: '11 960 ₽',
        click: false,
        quantity: 0,
        id: 'id12',
    },
    {
        img: '/public/image13.png',
        name: 'МФУ лазерный CANON i-Sensys MF445dw, A4, лазерный, черный',
        price: '35 310 ₽',
        click: false,
        quantity: 0,
        id: 'id13',
    },
    {
        img: '/public/image14.png',
        name: 'Смарт-часы AMAZFIT Bip U, 1.43", зеленый / зеленый',
        price: '4490 ₽',
        click: false,
        quantity: 0,
        id: 'id14',
    },
    {
        img: '/public/image15.png',
        name: 'Кофемашина PHILIPS EP1224/00, серый/черный',
        price: '29 990 ₽',
        click: false,
        quantity: 0,
        id: 'id15',
    },
    {
        img: '/public/image16.png',
        name: 'Гироскутер MIZAR MZ10,5CN, 10.5", карбон',
        price: '12 990 ₽',
        click: false,
        quantity: 0,
        id: 'id16',
    }
];

export default data;